name: Secrets Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  secrets_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python dependencies
        run: pip install PyGithub

      - name: Run check_secrets.py and write output to secrets.txt and stdout
        run: |
          python3 presubmits/check_secrets.py | tee secrets.txt

      - name: Check for leaks, post comment, and set exit code
        run: |
          python3 presubmits/post_gitleaks_comment.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
